services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=civalue'
      - 'POSTGRES_PASSWORD=1314246'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5455:5432'
  data-team-service:
    image: 'data-team-service:latest' 
    environment:
      - 'SERVER_PORT=8081'
    ports:
      - '8081:8081'